<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);
require_once 'koneksi.php';

echo "Memulai eksekusi skrip database...<br>";

$queries = [
    // --- DROP TABEL LAMA ---
    "DROP TABLE notifications",
    "DROP TABLE messages",
    "DROP TABLE comments",
    "DROP TABLE likes",
    "DROP TABLE postingan",
    "DROP TABLE forums",
    "DROP TABLE users",
    "DROP TABLE roles",

    // --- CREATE TABLE ---
    "CREATE TABLE roles (
        role_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        role_name VARCHAR2(50) NOT NULL UNIQUE
    )",

    "CREATE TABLE users (
        user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR2(100),
        nama_lengkap VARCHAR2(255) NOT NULL,
        email VARCHAR2(255) NOT NULL,
        password VARCHAR2(255) NOT NULL,
        role_id NUMBER NOT NULL,
        avatar_url VARCHAR2(255) DEFAULT '/Sinergi/public/assets/images/',
        verifikasi_kode VARCHAR2(255),
        is_verif NUMBER(1) DEFAULT 0,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
        CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(role_id)
    )",

    "CREATE TABLE forums (
        forum_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        nama_forum VARCHAR2(255) NOT NULL,
        deskripsi CLOB,
        created_by_user_id NUMBER NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_forums_creator FOREIGN KEY (created_by_user_id) REFERENCES users(user_id)
    )",

    "CREATE TABLE postingan (
        post_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL,
        forum_id NUMBER NULL,
        konten VARCHAR2(1000),
        post_image VARCHAR2(500),
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_postingan_user FOREIGN KEY (user_id) REFERENCES users(user_id),
        CONSTRAINT fk_postingan_forum FOREIGN KEY (forum_id) REFERENCES forums(forum_id)
    )",

    "CREATE TABLE likes (
        id_likes NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_user NUMBER NOT NULL,
        id_postingan NUMBER NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
        CONSTRAINT fk_likes_user FOREIGN KEY (id_user) REFERENCES users(user_id) ON DELETE CASCADE,
        CONSTRAINT fk_likes_post FOREIGN KEY (id_postingan) REFERENCES postingan(post_id) ON DELETE CASCADE
    )",

    "CREATE TABLE comments (
        id_comments NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_user NUMBER NOT NULL,
        id_postingan NUMBER NOT NULL,
        isi_komen VARCHAR2(500) NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
        CONSTRAINT fk_comment_user FOREIGN KEY (id_user) REFERENCES users(user_id) ON DELETE CASCADE,
        CONSTRAINT fk_comment_post FOREIGN KEY (id_postingan) REFERENCES postingan(post_id) ON DELETE CASCADE
    )",

    "CREATE TABLE messages (
        message_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        forum_id NUMBER NOT NULL,
        sender_id NUMBER NOT NULL,
        isi_pesan CLOB NOT NULL,
        parent_message_id NUMBER NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_messages_forum FOREIGN KEY (forum_id) REFERENCES forums(forum_id),
        CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(user_id),
        CONSTRAINT fk_messages_parent FOREIGN KEY (parent_message_id) REFERENCES messages(message_id)
    )",

    "CREATE TABLE notifications (
        notif_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL,
        type VARCHAR2(50) NOT NULL,
        related_post_id NUMBER NULL,
        related_user_id NUMBER NULL,
        related_forum_id NUMBER NULL,
        is_read NUMBER(1) DEFAULT 0 NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(user_id),
        CONSTRAINT fk_notif_related_post FOREIGN KEY (related_post_id) REFERENCES postingan(post_id),
        CONSTRAINT fk_notif_related_user FOREIGN KEY (related_user_id) REFERENCES users(user_id),
        CONSTRAINT fk_notif_related_forum FOREIGN KEY (related_forum_id) REFERENCES forums(forum_id)
    )",

    // --- ISI DATA AWAL ---
    "INSERT INTO roles (role_name) VALUES ('Mahasiswa')",
    "INSERT INTO roles (role_name) VALUES ('Dosen')",
    "INSERT INTO roles (role_name) VALUES ('Alumni')",
    "INSERT INTO roles (role_name) VALUES ('Mitra Industri')",
    "INSERT INTO roles (role_name) VALUES ('Admin')",
    "COMMIT",

    // Dummy user (gunakan hash password nanti)
    "INSERT INTO users (role_id, nama_lengkap, username, email, password) 
     VALUES (1, 'Achonk Ganteng', 'achonk', 'achonk@test.com', 'HASH_PASSWORD_123')",
    "INSERT INTO users (role_id, nama_lengkap, username, email, password) 
     VALUES (2, 'Budi Dosen', 'budi_dosen', 'budi@test.com', 'HASH_PASSWORD_123')",
    "COMMIT",

    "INSERT INTO forums (nama_forum, deskripsi, created_by_user_id) 
     VALUES ('PHP Native Dasar', 'Diskusi dasar-dasar PHP tanpa framework', 2)",
    "COMMIT",

    "INSERT INTO postingan (user_id, forum_id, konten, post_image) 
     VALUES (1, 1, 'Bagaimana cara koneksi ke Oracle pakai OCI8?', NULL)",
    "INSERT INTO postingan (user_id, forum_id, konten, post_image) 
     VALUES (1, NULL, 'Ini postingan di feed umum.', '/Sinergi/public/assets/images/jkw.jpeg')",
    "COMMIT",

    "INSERT INTO comments (id_user, id_postingan, isi_komen) VALUES (2, 1, 'Mantap postingan pertamanya!')",
    "COMMIT",

    "INSERT INTO likes (id_user, id_postingan) VALUES (2, 1)",
    "COMMIT",

    "INSERT INTO messages (forum_id, sender_id, isi_pesan) VALUES (1, 1, 'Halo, ada yang bisa bantu koneksi OCI8?')",
    "INSERT INTO messages (forum_id, sender_id, isi_pesan) VALUES (1, 2, 'Coba cek dokumentasi PHP, Achonk.')",
    "COMMIT"
];

// Eksekusi Query
foreach ($queries as $sql) {
    if (trim($sql) === '') continue;

    echo "Mengeksekusi: " . htmlspecialchars(substr(trim($sql), 0, 80)) . "... ";
    $stmt = oci_parse($conn, $sql);

    if (@oci_execute($stmt, OCI_NO_AUTO_COMMIT)) {
        if (strtoupper(trim($sql)) === 'COMMIT') {
            oci_commit($conn);
            echo "<span style='color: green;'>✅ Transaksi di-commit.</span><br>";
        } else {
            echo "<span style='color: green;'>✅ Berhasil.</span><br>";
        }
    } else {
        $e = oci_error($stmt);
        if (strpos(strtoupper(trim($sql)), 'DROP TABLE') === 0 && $e['code'] == 942) {
            echo "<span style='color: orange;'>⚠️ Tabel tidak ada (diabaikan).</span><br>";
        } else {
            echo "<span style='color: red;'>❌ Gagal: " . htmlentities($e['message'], ENT_QUOTES) . "</span><br>";
            oci_rollback($conn);
            oci_close($conn);
            die("Eksekusi dihentikan karena error.");
        }
    }
    oci_free_statement($stmt);
}

echo "Eksekusi skrip database selesai.<br>";
oci_close($conn);
?>
