<?php
require_once '../../config/koneksi.php';

// tabel users
$sql_users = "
CREATE TABLE users (
    id_users NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    nama_lengkap VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(100) NOT NULL,
    avatar_url VARCHAR2(255) DEFAULT '/Sinergi/public/assets/images/',
    verifikasi_kode VARCHAR2(255),
    is_verif NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// tabel forums
$sql_forums = "
CREATE TABLE forums (
    id_forums NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_forum VARCHAR2(255) NOT NULL,
    tipe_forum VARCHAR2(255) NOT NULL,
    deskripsi VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// tabel postingan
$sql_postingan = "
CREATE TABLE postingan (
    id_postingan NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user NUMBER NOT NULL,          
    konten VARCHAR2(1000),            
    post_image VARCHAR2(500),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP 
)
";

//tabel likes
$sql_likes = "
CREATE TABLE likes (
    id_likes NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user NUMBER NOT NULL,              
    id_postingan NUMBER NOT NULL, 
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// tabel comments
$sql_comments = "
CREATE TABLE comments (
    id_comments NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user NUMBER NOT NULL,              
    id_postingan NUMBER NOT NULL,
    isi_komen VARCHAR2(500) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// tabel messages
$sql_messages = "
CREATE TABLE messages (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id NUMBER NOT NULL,
    sender_id NUMBER NOT NULL,
    isi_pesan CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

$queries = [$sql_users, $sql_forums, $sql_postingan, $sql_likes, $sql_comments, $sql_messages];

foreach ($queries as $sql) {
    $stmt = oci_parse($conn, $sql);
    if (oci_execute($stmt)) {
        echo "✅ Tabel berhasil dibuat.<br>";
    } else {
        $e = oci_error($stmt);
        echo "❌ Error membuat tabel: " . htmlentities($e['message'], ENT_QUOTES) . "<br>";
    }
    oci_free_statement($stmt);
}

oci_close($conn);
?>
