<?php
require_once '../../config/koneksi.php';

// Buat tabel users
$sql_users = "
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_lengkap VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(100) NOT NULL,
    verifikasi_kode VARCHAR2(255),
    is_verif NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// Buat tabel forums
$sql_forums = "
CREATE TABLE forums (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_forum VARCHAR2(255) NOT NULL,
    tipe_forum VARCHAR2(255) NOT NULL,
    deskripsi VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// Buat tabel postingan
$sql_postingan = "
CREATE TABLE postingan (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    konten VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// Buat tabel likes
$sql_likes = "
CREATE TABLE likes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// Buat tabel comments
$sql_comments = "
CREATE TABLE comments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isi_komen VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// Buat tabel messages
$sql_messages = "
CREATE TABLE messages (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id NUMBER NOT NULL,
    sender_id NUMBER NOT NULL,
    isi_pesan CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
)
";

// Jalankan semua query satu per satu
$queries = [$sql_users, $sql_forums, $sql_postingan, $sql_likes, $sql_comments, $sql_messages];

foreach ($queries as $sql) {
    $stmt = oci_parse($conn, $sql);
    if (oci_execute($stmt)) {
        echo "✅ Tabel berhasil dibuat.<br>";
    } else {
        $e = oci_error($stmt);
        echo "❌ Error membuat tabel: " . htmlentities($e['message'], ENT_QUOTES) . "<br>";
    }
    oci_free_statement($stmt);
}

oci_close($conn);
?>
